export enum postTypes {
  FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE = "FETCH_POST_FAILURE",
}

export enum commentsTypes {
  FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST",
  FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS",
  FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE",
}

export enum userTypes {
  FETCH_POST_REQUEST = "USER_FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS = "USER_FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE = "USER_FETCH_POST_FAILURE",
}
